services:
  tno_pipelines:
    image: tno_pipelines
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - .:/app
    # environment:
    #   - FLASK_APP=app.py
    #   - FLASK_ENV=development
    #   - FLASK_DEBUG=1
    command: /bin/sh -c "while sleep 1000; do :; done"
