services:
  tno_pipelines:
    image: tno_pipelines
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - .:/app
    command: /bin/sh -c "while sleep 1000; do :; done"
