"""
A Python module for managing astronomical datasets generated by the 'geradata'
Fortran executable. It provides efficient caching using Parquet and handles
program dependencies intelligently.
"""

import pathlib
import subprocess
import pandas as pd
from datetime import datetime, date, timedelta, time
import os
import glob
import io
import logging


def get_config():
    """Gets configuration from environment variables or uses default values."""

    parquet_dir = os.getenv('COMMON_INPUTS_DIR')
    if not parquet_dir:
        raise EnvironmentError("Environment variable 'COMMON_INPUTS_DIR' is not set.")

    return {
        'program_path': os.getenv('GERADATA_PROGRAM_PATH', "geradata"),
        'parquet_dir': parquet_dir,
    }

def get_program_directory(program_path):
    """Gets the absolute directory path where the program is located."""
    return os.path.dirname(os.path.abspath(program_path))

def generate_dataset(start_datetime, end_datetime, step_seconds, cwd, logger:logging.Logger):
    """
    Safely executes the Fortran program to generate a Parquet file.

    This function uses the 'cwd' argument to run the executable from its own
    directory, ensuring it finds its dependencies without altering the
    main script's working directory.
    """
    config = get_config()
    program_path =config['program_path']
    parquet_dir = config['parquet_dir']
    
    os.makedirs(parquet_dir, exist_ok=True)
    
    start_str = start_datetime.strftime('%Y-%b-%d %H:%M:%S.%f')[:-3]
    end_str = end_datetime.strftime('%Y-%b-%d %H:%M:%S.%f')[:-3]
    input_data = f"{start_str}\n{end_str}\n{step_seconds}\n"

    start_name = start_datetime.strftime('%Y%b%d').upper()
    end_name = end_datetime.strftime('%Y%b%d').upper()
    parquet_file = os.path.join(parquet_dir, f"dates_{start_name}_{end_name}_{step_seconds}s.parquet")
    
    try:
        logger.info("Running geradata Fortran program.")
        result = subprocess.run(
            [program_path],
            input=input_data,
            text=True,
            check=True,
            timeout=300,
            cwd=cwd,
            capture_output=True
        )
        
        # Use an in-memory buffer to avoid disk I/O and temporary files
        output_buffer = io.StringIO(result.stdout)

        df = pd.read_csv(output_buffer, sep=r'\s+', header=None, names=['date', 'time'], engine='python')
        
        # Manually parse date in a locale-independent and thread-safe way
        month_map = {
            'JAN': '01', 'FEB': '02', 'MAR': '03', 'APR': '04', 'MAY': '05', 'JUN': '06',
            'JUL': '07', 'AUG': '08', 'SEP': '09', 'OCT': '10', 'NOV': '11', 'DEC': '12'
        }
        date_parts = df['date'].str.split('-', expand=True)
        # A lógica original estava incorreta. Corrigido para mapear a coluna do mês.
        month_num = date_parts[1].str.upper().map(month_map)
        formatted_date_str = date_parts[0] + '-' + month_num + '-' + date_parts[2]
        
        df['timestamp'] = pd.to_datetime(
            formatted_date_str + ' ' + df['time'],
            format='%Y-%m-%d %H:%M:%S.%f'
        )
        
        df[['timestamp']].to_parquet(parquet_file, engine='pyarrow', index=False)
        return parquet_file
        
    except FileNotFoundError:
        raise FileNotFoundError(f"Program not found at '{program_path}'")
    except subprocess.CalledProcessError as e:
        error_output = e.stderr if e.stderr else "No error output captured."
        raise RuntimeError(f"Fortran program failed with exit code {e.returncode}. Error: {error_output}")
    except Exception as e:
        raise RuntimeError(f"Dataset generation failed: {e}")
    finally:
        # No cleanup needed as no temporary files or global state changes were made
        pass

def get_required_range(start_query, end_query):
    """Determines the ideal Parquet cache range to cover the query."""
    current_year = date.today().year
    start_year = min(start_query.year, current_year)
    end_year = max(end_query.year, current_year + 3)
    return datetime(start_year, 1, 1), datetime(end_year + 1, 1, 1)

def find_parquet_for_range(start_needed, end_needed, step, parquet_dir=None):
    """Finds an existing Parquet file that covers the required interval."""
    config = get_config()
    parquet_dir = parquet_dir or config['parquet_dir']
    
    pattern = os.path.join(parquet_dir, f"dates_*_*_{step}s.parquet")
    for file in glob.glob(pattern):
        try:
            basename = os.path.basename(file)
            parts = basename.replace('.parquet', '').split('_')
            # A função strptime espera uma string, não uma lista.
            # Corrigido para usar os índices corretos da lista 'parts'.
            file_start = datetime.strptime(parts[1], '%Y%b%d')
            file_end = datetime.strptime(parts[2], '%Y%b%d')
            
            if file_start <= start_needed and file_end >= end_needed:
                return file
        except (ValueError, IndexError):
            continue
    return None

def query_dates(start_interval: datetime, end_interval: datetime, step: int,
                cwd: pathlib.Path, logger:logging.Logger):
    """
    Queries astronomical data, generating a Parquet cache if needed,
    and exports the result to a text file.
    """
    output_filepath = pathlib.Path(cwd).joinpath("dates.txt")

    if start_interval >= end_interval:
        raise ValueError("Start date must be before end date.")

    if end_interval.time() == time(0, 0, 0):
        end_interval = end_interval.replace(hour=23, minute=59, second=59)

    start_needed, end_needed = get_required_range(start_interval, end_interval)
    
    logger.debug(f"Query range: {start_interval.strftime('%Y-%m-%d %H:%M')} to {end_interval.strftime('%Y-%m-%d %H:%M')}")
    logger.debug(f"Required cache range: {start_needed.strftime('%Y-%m-%d')} to {end_needed.strftime('%Y-%m-%d')}")
        
    parquet_file = find_parquet_for_range(start_needed, end_needed, step)
    
    if not parquet_file:

        logger.info(f"Parquet cache not found. Generating new dataset")
        parquet_file = generate_dataset(start_needed, end_needed, step, cwd, logger)

        logger.info(f"Cache generated: {parquet_file}")
    else:
        logger.info(f"Using existing cache: {parquet_file}")


    delta_seconds = timedelta(seconds=step)
    df = pd.read_parquet(
        parquet_file,
        filters=[('timestamp', '>=', start_interval - delta_seconds), ('timestamp', '<=', end_interval + delta_seconds)]
    )
    
    if df.empty:
        # Falhou ao gerar o intervalo de datas solicitado
        raise Exception("Dataset generation failed to produce any data")
    
    # Format the output to match the original Fortran program's style
    formatted = df['timestamp'].dt.strftime('%Y-%b-%d %H:%M:%S.%f').str.upper().str[:-3]
    formatted.to_csv(output_filepath, header=False, index=False)

    logger.debug(f"Exported {len(df)} records to {output_filepath}")
    logger.info(f"Dates file generated successfully. [{output_filepath}]")

    return output_filepath




