#!/usr/bin/env python3

import argparse
import os
import sys
from pathlib import Path
from datetime import datetime
import pandas as pd
from sqlalchemy.orm import Session

# # Add the packages directory to the Python path
# script_dir = Path(__file__).resolve().parent
# packages_dir = script_dir.parent / "packages"
# sys.path.insert(0, str(packages_dir))

# Import from packages directory
from utils import check_planetary_ephemeris_file, load_yml, setup_logger, load_json, get_asteroid_inputs_dir, check_leap_seconds_file
from library import asteroid_diameter, read_ra_dec_from_ephemerides, object_diameter_plus_error
from asteroid_ephemeris import check_asteroid_ephemeris, check_uncertainty_file
import geradata
from generate_ephemeris import generate_ephemeris_file
from praia_occ import search_candidates
from star_catalog import generate_star_catalog
from path_coeff import execute_path_coeff, prepare_occultation_table_dataframe

from dao.task import TaskDao, PredictionState


class Runner:

    def __init__(self, config) -> None:
        # Loading config
        self.config = load_yml(config)

        self.cwd = self.config.get('asteroid_path')

        self.logger = setup_logger("predict", logdir=self.cwd)

        self.task_dao = TaskDao()
        self.db_session = Session(self.task_dao.get_db_engine())

    def __enter__(self):
        return self

    def run(self):
        """Run Hello World"""
        self.logger.info("="*50)
        self.logger.info("Running Predict Occultation")
        self.logger.info("="*50)
        self.logger.info(f"cwd: {self.cwd}")
        # self.logger.info(f"Asteroid Name: {self.config.get('asteroid_name')}")

        # Update task status to RUNNING
        self.logger.info(f"Updating task status to RUNNING. Task ID: [{self.config.get('task_id')}]")
        self.task_dao.update_task_status(
            db_session=self.db_session, 
            task_id=self.config.get('task_id'), 
            new_state=PredictionState.RUNNING
        )


        # Read asteroid json with all the data
        self.logger.info("Reading asteroid.json file")
        # TODO: Validar o formato do asteroid.json
        data = load_json(Path(self.cwd).joinpath("asteroid.json"))

        # Parametros do asteroide
        asteroid = data["asteroid"]
        # Principais parâmetros para a predição
        predict_params = data["predict_params"]
        # Periodo para o qual a predição será feita
        START_DATE = predict_params["start_date"]
        END_DATE = predict_params["end_date"]
        EPHEMERIS_STEP = predict_params.get("ephemeris_step", 60)
        MAXIMUM_VISUAL_MAGNITUDE = predict_params.get("maximum_visual_magnitude", 18) # type: ignore
        PROPER_MOTION_COMPENSATION = predict_params.get("proper_motion_compensation") # type: ignore

        planetary_ephemeris_info = predict_params["planetary_ephemeris"]
        leap_seconds_info = predict_params["leap_seconds"]
        star_catalog_params = predict_params["star_catalog"]

        # Diretório de inputs externos dos asteroids (bsp, apmag_and_uncertainties, etc)
        ASTEROID_INPUTS_DIR = get_asteroid_inputs_dir(data["alias"])
        self.logger.info(f"Asteroid inputs dir: {ASTEROID_INPUTS_DIR}")


        # ---------------------------------------------------------------------
        #region Check asteroid ephemeris file (bsp) exists and is valid for the required period
        # and create a symbolic link to the execution directory if valid
        self.logger.info("Checking asteroid ephemeris file")
        asteroid_ephemeris_info = predict_params["asteroid_ephemeris"]

        # Local onde estão os arquivos bsp, apmag_and_uncertainties, etc previamente baixados
        bsp_filename = asteroid_ephemeris_info["filename"]
        original_bsp_filepath = Path(ASTEROID_INPUTS_DIR, bsp_filename)  # type: ignore

        check_asteroid_ephemeris(
            bsp_filepath=original_bsp_filepath,
            bsp_period_start=asteroid_ephemeris_info["start_period"],
            bsp_period_end=asteroid_ephemeris_info["end_period"],
            required_period_start=START_DATE,
            required_period_end=END_DATE,
        )
        self.logger.info(f"Asteroid ephemeris data is available for the period {START_DATE} to {END_DATE}.")

        # Cria links simbólicos para o arquivos bsp no diretório de execução
        ASTEROID_EPHEMERIS_FILEPATH = Path(self.cwd, original_bsp_filepath.name)
        self.logger.info(f"Creating link to asteroid ephemeris file. {original_bsp_filepath} -> {ASTEROID_EPHEMERIS_FILEPATH}")
        os.symlink(original_bsp_filepath, ASTEROID_EPHEMERIS_FILEPATH)
        #endregion

        # ---------------------------------------------------------------------
        #region Check asteroid uncertainty file exists
        self.logger.info("Checking asteroid uncertainty file")
        uncertainty_filename = asteroid_ephemeris_info["mag_and_uncert_filename"]
        original_uncertainty_filepath = Path(ASTEROID_INPUTS_DIR, uncertainty_filename)  # type: ignore

        check_uncertainty_file(original_uncertainty_filepath)
        self.logger.info(f"Asteroid uncertainty file is available: {original_uncertainty_filepath}")

        # Cria links simbólicos para o arquivos apmag_and_uncertainties no diretório de execução
        APMAG_UNCERTAINTY_FILEPATH = Path(self.cwd, original_uncertainty_filepath.name)
        self.logger.info(f"Creating link to asteroid uncertainty file. {original_uncertainty_filepath} -> {APMAG_UNCERTAINTY_FILEPATH}")
        os.symlink(original_uncertainty_filepath, APMAG_UNCERTAINTY_FILEPATH)
        #endregion

        # ---------------------------------------------------------------------
        #region Check Planetary Ephemeris file exists and create a symbolic link to the execution directory
        self.logger.info("Checking planetary ephemeris file")
        planetary_ephemeris_filename = planetary_ephemeris_info.get("filename")
        original_planetary_ephemeris_filepath = check_planetary_ephemeris_file(planetary_ephemeris_filename)
        self.logger.info(f"Planetary ephemeris file is available: {original_planetary_ephemeris_filepath}")

        # Cria links simbólicos para o arquivos planetary ephemeris no diretório de execução
        PLANETARY_EPHEMERIS_FILEPATH = Path(self.cwd, original_planetary_ephemeris_filepath.name)
        self.logger.info(f"Creating link to planetary ephemeris file. {original_planetary_ephemeris_filepath} -> {PLANETARY_EPHEMERIS_FILEPATH}")
        os.symlink(original_planetary_ephemeris_filepath, PLANETARY_EPHEMERIS_FILEPATH)
        #endregion

        # ---------------------------------------------------------------------
        #region Check Leap Seconds file exists and create a symbolic link to the execution directory
        self.logger.info("Checking leap seconds file")
        leap_seconds_filename = leap_seconds_info.get("filename")
        original_leap_seconds_filepath = check_leap_seconds_file(leap_seconds_filename)
        self.logger.info(f"Leap seconds file is available: {original_leap_seconds_filepath}")

        # Cria links simbólicos para o arquivos leap seconds no diretório de execução
        LEAP_SECONDS_FILEPATH = Path(self.cwd, original_leap_seconds_filepath.name)
        self.logger.info(f"Creating link to leap seconds file. {original_leap_seconds_filepath} -> {LEAP_SECONDS_FILEPATH}")
        os.symlink(original_leap_seconds_filepath, LEAP_SECONDS_FILEPATH)
        #endregion

        # ---------------------------------------------------------------------
        #region Create dates file for the specified period

        # Verifica no diretório de inputs se existe um arquivo dates que contenha o periodo necessário
        # para a predição. Se existir, faz um subset com o periodo necessário e cria um novo arquivo dates.txt no diretório de execução.
        # valida se o subset tem todo o periodo necessário.
        self.logger.info("Creating dates file")
        DATES_FILEPATH = geradata.query_dates(
            start_interval=datetime.strptime(START_DATE, "%Y-%m-%d"),
            end_interval=datetime.strptime(END_DATE, "%Y-%m-%d"),
            step=EPHEMERIS_STEP,
            cwd=self.cwd,
            logger=self.logger,
        )

        #endregion

        # ---------------------------------------------------------------------
        #region Criação do arquivo de ephemeris
        
        ephemeris_filepath = generate_ephemeris_file(
            dates_filepath=DATES_FILEPATH,
            object_ephemeris=ASTEROID_EPHEMERIS_FILEPATH,
            planetary_ephemeris=PLANETARY_EPHEMERIS_FILEPATH,
            leap_seconds=LEAP_SECONDS_FILEPATH,
            cwd=self.cwd, 
            logger=self.logger
        )
        # TODO: Verificar se o arquivo de ephemeris tem valores/estrutura valida.
        #endregion


        # ---------------------------------------------------------------------
        #region Criação do catalogo de estrelas

        # TODO: otimizar a query no gaia com base no tamanho aparente do objeto no ceu (rodrigo)
        # BUSCA USANDO QC3 POLIGONO calculando tamanho aparante (objeto+terra+objeto)
        self.logger.info("Calculate the diameter of the asteroid.")
        
        ast_diameter = asteroid_diameter(
            diameter=asteroid.get("diameter", None), 
            density_err_max=asteroid.get("density_err_max", None))
        
        self.logger.debug(f"Asteroid diameter: {ast_diameter}")

        self.logger.info(f"Reading ephemeris file and calculating positions")
        ra, dec, angular_diameter = read_ra_dec_from_ephemerides(
            input=ephemeris_filepath,
            object_diameter = ast_diameter,
            h = asteroid.get("h", None),
            proper_motion_compensation = PROPER_MOTION_COMPENSATION,
        )
        self.logger.debug(f"Positions: [{len(ra)}]")

        self.logger.info(f"Generating star catalog.")

        star_catalog_cat_filepath, star_catalog_csv_filepath = generate_star_catalog(
            ra = ra, # type: ignore
            dec = dec, # type: ignore
            angular_diameter = angular_diameter, # type: ignore
            maximum_visual_magnitude = MAXIMUM_VISUAL_MAGNITUDE,
            catalog_name=star_catalog_params.get("name"),
            catalog_display_name=star_catalog_params.get("display_name"),
            catalog_schema=star_catalog_params.get("schema"),
            catalog_tablename=star_catalog_params.get("tablename"),
            catalog_ra_property=star_catalog_params.get("ra_property"),
            catalog_dec_property=star_catalog_params.get("dec_property"),
            cwd=self.cwd,
            logger=self.logger
        )
        #endregion


        # ---------------------------------------------------------------------
        #region Search Candidates - Execução do PRAIA OCC

        # Quando o diametro do objeto exitir no json, ele é passado para a função search_candidates
        # que cria o arquivo praia_occ_star_search_12.dat. Sua função é reduzir o numero de calculo necessário
        # especialmente para objetos de diametros pequenos.
        self.logger.info("Calculate object diameter + error")
        object_diameter = object_diameter_plus_error(
            asteroid.get("diameter", None), 
            asteroid.get("diameter_err_max", None)
        )
        self.logger.debug(f"Object diameter: {object_diameter}")

        self.logger.info("Search Candidates using PRAIA OCC")
        occultation_filepath = search_candidates(
            star_catalog_filepath=star_catalog_cat_filepath,
            ephemeris_filepath=ephemeris_filepath,
            object_diameter=object_diameter,
            cwd=self.cwd,
            logger=self.logger
        )

        # IMPORTANT! If the occultation file is empty, skip next steps.
        if pd.read_csv(occultation_filepath).empty:
            return
        #endregion


        # ---------------------------------------------------------------------
        #region Prepara a tabela de occultações 

        # Cria um novo dataframe a partir do arquivo de occultações. 
        # Adiciona todas as colunas que existem na tabela de predições do portal.
        # Como informações do asteroid, proveniencia e path_coeff.
        # IMPORTANT! Sobreescreve o arquivo csv de ocultações com as novas colunas.
        self.logger.info("Preparing occultation table")
        prepare_occultation_table_dataframe(
            occultation_table=occultation_filepath, 
            object_data=asteroid,
            predict_params=predict_params,
            job_id=self.config.get('job_id', None)
        )
        #endregion

        # ---------------------------------------------------------------------
        #region Calculating Path Coeff

        # IMPORTANT! Sobreescreve o arquivo csv de ocultações com as novas colunas.
        self.logger.info("Calculating Path Coefficients")
        occ_count = execute_path_coeff(
            object_data=asteroid,
            occultation_table=occultation_filepath,
            star_catalog=star_catalog_csv_filepath,
            object_ephemeris=ephemeris_filepath,
            mag_and_uncert=APMAG_UNCERTAINTY_FILEPATH,
            planetary_ephemeris=PLANETARY_EPHEMERIS_FILEPATH,
            leap_seconds=LEAP_SECONDS_FILEPATH,            
            logger=self.logger
        )
        #endregion

        self.logger.info(f"Total occultations found: {occ_count}")


    def __exit__(self, exc_type, exc_value, traceback):

        if exc_type:
            self.logger.error("%s: %s", exc_type.__name__, exc_value, exc_info=(exc_type, exc_value, traceback))            
            # Update task status to FAILED
            self.logger.info(f"Updating task status to FAILED. Task ID: [{self.config.get('task_id')}]")
            self.task_dao.mark_task_failed(
                db_session=self.db_session, 
                task_id=self.config.get('task_id'), 
                error_message=f"{exc_type.__name__}: {exc_value}"
            )

        else:
            # Update task status to WAITING_RESULTS
            self.logger.info(f"Updating task status to WAITING_RESULTS. Task ID: [{self.config.get('task_id')}]")
            self.task_dao.update_task_status(
                db_session=self.db_session, 
                task_id=self.config.get('task_id'), 
                new_state=PredictionState.WAITING_RESULTS
            )

        self.logger.info("done!")
            

if __name__ == "__main__":
    # Create the parser and add arguments
    parser = argparse.ArgumentParser()
    parser.add_argument(dest="config_path", help="yaml config path")

    # # Orchestration proccess dir
    # parser.add_argument(
    #     dest="cwd", nargs="?", help="processing dir", default=os.getcwd()
    # )

    args = parser.parse_args()
    config_path = args.config_path

    # Run pipeline
    with Runner(config_path) as hwrun:
        hwrun.run()
