name: pipe_pred_occ
channels:
  - defaults
dependencies:
  - python=3.12
  - pip==25.0
  - setuptools==75.8.0
  - pip:
      - PyYaml==6.0.2
      - pydantic==2.10.6
      - sqlalchemy==2.0.39
      - psycopg2==2.9.10
      - psycopg2-binary==2.9.10
      - numpy==2.2.3
      - pandas==2.2.3
      - spiceypy==5.0.1
      - astropy==7.0.1
      - scipy==1.15.2